### ISSUE TITLE
how to catch on close event and recreate the socket?

### ISSUE THREAD

**Issue by svenwoldt** [PeterKassenaar/ng2-websockets#1]
how to catch on close event and recreate the socket if it is quit.
thank you for your help

**Comment by PeterKassenaar** [comment]
I'm currently looking in to that. I noticed the server crashes if you close the browser connection. Will investigate. Pointers are welcomed.

**Comment by PeterKassenaar** [comment]
Fixed as of Feb. 3, 2017.
