### ISSUE TITLE
How to pass headers to the WebSocket URL?

### ISSUE THREAD

**Issue by VikramK** [PeterKassenaar/ng2-websockets#2]
Need to send authToken in the header

**Comment by svenwoldt** [comment]
Wont work!
No common browser supports that yet.
Possible solution:
Send the auth token with each message over the socket 
or 
create an authenticated http ticket system for the socket connection

**Comment by PeterKassenaar** [comment]
As far as I know svenwoldt is correct. You would need to work with JWT and send this in in each message to the socket server. Subsequently do JWT validation on your server. 

Closing the issue for now, but feel free to reopen if you think this is appropriate.
