### ISSUE TITLE
Proxy Websocket

### ISSUE THREAD

**Issue by mburger81** [PeterKassenaar/ng2-websockets#3]
Does the lib support proxy a Websocket with angular2 + webpack dev server?

If not can you include it?

**Comment by PeterKassenaar** [comment]
It does currently not support WebPack. You can do so yourself by starting a new project with angular-cli and copy/paste the client-code to the new project. I used it without angular-cli at the moment. I don't have plans to include this at the moment. Thanks - closing it for now. P.
